### ISSUE TITLE
RemoteRobot keywords pass if exception is raised

### ISSUE THREAD

**Issue by espositocode** [zimmermanncode/robotframework-tools#2]
I have a simple RemoteRobot server running with multiple libraries, and it is successfully executing keywords on the remote host. However, I noticed that if I raise an exception from my keyword, the test will continue to run successfully. When I check the log.html, I can see the exception details from my keyword, but the keyword is actually listed as a success and continues to run the test.

I tried running my exact same test library on the original RobotRemoteServer, and exceptions were handled just fine (the keyword/test failed). It was only when I switched to RemoteRobot that keywords started to pass incorrectly. (FYI the reason I switched to using this library was for multiple library support.)

The exceptions I attempted to raise were ValueError and AssertionError.

**Comment by joongh** [comment]
I have exactly same experience as you have, and this issue have been fixed once at version 0.1a132.
It was doing ok with robotframework 2.9. But since robotframework 3.0, this issue has occurred again.
This is because of the modification of some class name in robotframework.
If you need more information, see #1 . This issue is same issue as #1 .

**Comment by espositocode** [comment]
@joongh Ah ok, I didn't realize #1 was the same problem. I'll close this issue as a duplicate. Thanks!
